[build]
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.136.5"
  HUGO_ENABLEGITINFO = "true"
  
[context.production.environment]
  HUGO_ENV = "production"
  URL = "https://www.alicefedotova.com"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "http://*"
  to = "https://www.alicefedotova.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://alicefedotova.com/*"
  to = "https://www.alicefedotova.com/:splat"
  status = 301
  force = true
